export const NAME = 'name';
export const MONEY = 'money';
export const SPECIAL_CARDS = 'specialCards';
export const COLOR = 'color';
export const FIELD_NR = 'fieldNr';
export const IS_IN_PRISON ='isInPrison';
export const NR_TURNS_TO_WAIT = 'nrTurnsToWait';
export const IS_GAME_LOST = 'isGameLost';
export const STRATEGY = 'strategy';
