export const PAY = 'pay';
export const PASSING_START = 'passingStart';
export const VISITING_ESTATE = 'visitingOtherPlayersEstate';
export const CHANCE_CARD_PAYMENT = 'chanceCardPayment';
export const SELL_BUILDINGS = 'sellBuildings';
export const BUY_ESTATE ='buyEstate';
export const SELL_ESTATES = 'sellEstates';
export const PLEGDE_ESTATES = 'plegdeEstates';
export const UNPLEGDE_ESTATES = 'unplegdeEstates';
export const GET_MONEY = 'getMoney';
export const GO_TO_JAIL = 'goToJail';
export const SPECIAL_CARDS = 'specialCards';
export const MOVE = 'move';
export const END_PHASE = 'endPhase';
export const REASON = 'reason'
export const IS_MANDATORY = 'isMandatory';
export const TYPE = 'type';
export const PAYLOAD = 'payload';
